//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bocchidesu_coctothorpe {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class txt {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal txt() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Bocchidesu_coctothorpe.txt", typeof(txt).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 
        ///127.0.0.1 discordapp.com
        ///127.0.0.1 discord.com
        ///127.0.0.1 updates.discord.com
        ///127.0.0.1 dl.discordapp.net
        ///127.0.0.1 blog.discord.com
        ///127.0.0.1 medium.com
        ///127.0.0.1 gateway.discord.gg
        ///127.0.0.1 media.discordapp.net
        ///127.0.0.1 images-ext-2.discordapp.net
        ///127.0.0.1 images-ext-1.discordapp.net
        ///127.0.0.1 url9177.discordapp.com
        ///127.0.0.1 canary-api.discordapp.com
        ///127.0.0.1 cdn-ptb.discordapp.com
        ///127.0.0.1 ptb.discordapp.com
        ///127.0.0.1 status.discordapp.com
        ///127.0.0.1 cdn-canary.discordapp.com
        ///127.0.0.1 cdn.discordap [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        public static string discord {
            get {
                return ResourceManager.GetString("discord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 
        ///127.0.0.1 duckduckgo.com #duckduckgo
        ///127.0.0.1 external-content.duckduckgo.com #duckduckgo
        ///127.0.0.1 improving.duckduckgo.com #duckduckgo 的本地化字符串。
        /// </summary>
        public static string duckduckgo {
            get {
                return ResourceManager.GetString("duckduckgo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 
        ///127.0.0.1 exhentai.org #exhentai
        ///127.0.0.1 e-hentai.org #exhentai
        ///127.0.0.1 forums.e-hentai.org #exhentai 的本地化字符串。
        /// </summary>
        public static string exhentai {
            get {
                return ResourceManager.GetString("exhentai", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 
        ///127.0.0.1 uploads.github.com #github
        ///127.0.0.1 api.funcaptcha.com #github
        ///127.0.0.1 media.githubusercontent.com #github
        ///127.0.0.1 camo.githubusercontent.com #github
        ///127.0.0.1 github.com #github
        ///127.0.0.1 nodeload.github.com #github
        ///127.0.0.1 api.github.com #github
        ///127.0.0.1 codeload.github.com #github
        ///127.0.0.1 raw.github.com #github
        ///127.0.0.1 training.github.com #github
        ///127.0.0.1 assets-cdn.github.com #github
        ///127.0.0.1 documentcloud.github.com #github
        ///127.0.0.1 help.github.com #github
        ///127.0.0.1 githubstat [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        public static string github {
            get {
                return ResourceManager.GetString("github", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 
        ///127.0.0.1 onedrive.live.com #ms
        ///127.0.0.1 skyapi.onedrive.live.com #ms
        ///127.0.0.1 1drv.ms #ms 的本地化字符串。
        /// </summary>
        public static string ms {
            get {
                return ResourceManager.GetString("ms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 
        ///127.0.0.1	nyaa.si #nyaa
        ///127.0.0.1	www.nyaa.si #nyaa
        ///127.0.0.1	sukebei.nyaa.si #nyaa 的本地化字符串。
        /// </summary>
        public static string nyaa {
            get {
                return ResourceManager.GetString("nyaa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 
        ///127.0.0.1       pixiv.net  #pixiv
        ///127.0.0.1       www.pixiv.net  #pixiv
        ///127.0.0.1       ssl.pixiv.net #pixiv
        ///127.0.0.1       accounts.pixiv.net  #pixiv
        ///127.0.0.1       touch.pixiv.net #pixiv
        ///127.0.0.1       oauth.secure.pixiv.net  #pixiv
        ///127.0.0.1       dic.pixiv.net #pixiv
        ///127.0.0.1       en-dic.pixiv.net  #pixiv
        ///127.0.0.1       sketch.pixiv.net #pixiv
        ///127.0.0.1       payment.pixiv.net #pixiv
        ///127.0.0.1       factory.pixiv.net  #pixiv
        ///127.0.0.1       comic.pixiv.net   #pixiv
        ///127.0.0.1       novel.pixiv.net [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        public static string pixiv {
            get {
                return ResourceManager.GetString("pixiv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 
        ///127.0.0.1 store.steampowered.com #steam
        ///127.0.0.1 steampowered.com #steam
        ///127.0.0.1 steamcommunity.com #steam 的本地化字符串。
        /// </summary>
        public static string steam {
            get {
                return ResourceManager.GetString("steam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 
        ///127.0.0.1 v2ex.com #v2ex
        ///127.0.0.1 cdn.v2ex.com #v2ex 的本地化字符串。
        /// </summary>
        public static string v2ex {
            get {
                return ResourceManager.GetString("v2ex", resourceCulture);
            }
        }
    }
}
